### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by mediaminister**
This pull request includes:
- require new inputstreamhelper 0.3.5 fixing https://github.com/pietje666/plugin.video.vrt.nu/issues/440
- new fix for webscraper after VRT NU changed html again

### CODE REVIEW

**Comment by dagwieers** [comment]
Should we release v2.2.1 before v2.2.0 is out ?

**Comment by mediaminister** [comment]
This should be released as it fixes a broken tv guide and livestreams in 2.0.0. Maybe patching 2.0.0 is a better idea?

**Comment by dagwieers** [comment]
I am afraid I already put the v2.2.0 release on Facebook, so people may already have it installed.
That's why I think we need to call it v2.2.1. In itself not a big deal, but v2.2.0 is being delayed as well.

**Comment by mediaminister** [comment]
Okay, no problem.

**Pull request merged**
