### PR TITLE
WIP: Fix known cosmetic issues

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Disable menu caching for Main menu
- Disable menu caching for My favorites submenu
- Rename A-Z to 'All programs' (retained in icon and breadcrumbs)
- Change 'select' controls into 'enum' controls in settings

### CODE REVIEW

**Comment by dagwieers** [comment]
It would be nice if we could invalidate the menu caches e.g. when settings change. That would be more efficient than disabling menu caching for some of the directories that only change due to settings.

**Comment by michaelarnauts** [comment]
Doesn't this already happen here https://github.com/pietje666/plugin.video.vrt.nu/blob/ff28b8393f8d0a21ba0297de4a1fe806b2363c3b/resources/lib/service.py#L53 ?

**Comment by dagwieers** [comment]
@michaelarnauts Those are the HTTP caches that we manage ourselves. But Kodi also has a menu cache built-in (endOfDirectory), that we use for menus that do not change. But our main menu and favorites menu only changes when you modify settings (which is very infrequently) and currently we are forced to disable menu caching, while if we could invalidate the menu cache ourselves, those menus would be even faster when cached.

**Comment by dagwieers** [comment]
In this PR I tried two things that did not work:
- Move the selection to a specific ListItem (for the TV Guide to default to Today)
- Add support for label2Mask (use %D when Unsorted) so we can keep the original title names

Both failed, even on Kodi v18.4. The latter test I need to remove.

**Comment by mediaminister** [comment]
So, is it useful that I add commits to this branch? I'm fixing the "Universiteit van Vlaanderen" Up Next bug.

**Comment by dagwieers** [comment]
@mediaminister I would fix bugs in separate PRs. It is going to be a lot easier if you have a working fix. And reference the PR numbers in the tracking issue so we can verify merged fixes work.

**Comment by dagwieers** [comment]
Another test is to add `sys.exit()` to end the thread explicitly. However, I don't think that is actually needed, if stream_position ends the thread should end by itself. The question here is whether testing for `isPlaying()` every 500ms is really sufficient. If new videos are being played in quick succession, the threads could accumulate.

I think we should at least compare the file being played, or add a random number to the properties and verify if this has changed to know when to exit the thread..

Another option is to kill any pre-existing thread before starting a new one, so that at all times we know there is only one thread running (the latest one).

**Comment by mediaminister** [comment]
> The question here is whether testing for isPlaying() every 500ms is really sufficient. If new videos are being played in quick succession, the threads could accumulate.

I think this is not possible, there is always a "stop" event that triggers the playerinfo thread to quit.
And when a new video is played, a new playerinfo object is created.

**Comment by dagwieers** [comment]
So in order to avoid the additional `Container.Refresh` we need to make sure the internal resumepoints are updated when the directory gets refreshed by Kodi. I made the resumepoints update (online) async, and that increases our chances of this being the case, but it would be much better if we weren't reading the resume_points from disk almost every time we refresh e.g. Recent items in this case.

```
2019-10-26 19:18:16.914 T:1312813952  NOTICE: deleting video codec
2019-10-26 19:18:16.925 T:1937088528  NOTICE: VideoPlayer: finished waiting
2019-10-26 19:18:16.925 T:1937088528  NOTICE: CVideoPlayer::CloseFile()
2019-10-26 19:18:16.925 T:1937088528  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-26 19:18:16.927 T:1937088528  NOTICE: VideoPlayer: finished waiting
2019-10-26 19:18:17.254 T:1937088528   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-10-26 19:18:17.633 T:1673438080  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 606.51104736328125, 'total': 780.00006103515625, 'event': u'playbackstopped'}
2019-10-26 19:18:17.634 T:1673438080  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-5d08f592-c621-48dd-9942-0eb9da23f569&size=1
2019-10-26 19:18:18.010 T:1312813952  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-10-26 19:18:18.069 T:1312813952  NOTICE: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 4 minutes and 48 seconds.
2019-10-26 19:18:18.098 T:1312813952  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 3 minutes and 19 seconds.
2019-10-26 19:18:18.109 T:1312813952  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 48 minutes and 23 seconds.
2019-10-26 19:18:18.490 T:1673438080  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-10-26 19:18:18.855 T:1205302144  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-10-26 19:18:18.856 T:1205302144  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points/contentdamvrt20191010universiteitvanvlaanderen20192020a0009depotwp00160242
2019-10-26 19:18:18.856 T:1205302144  NOTICE: [plugin.video.vrt.nu] URL post data:: {"url": "/vrtnu/a-z/universiteit-van-vlaanderen/2019-2020/universiteit-van-vlaanderen-s2019-2020a9/", "position": 606.51104736328125, "total": 780.00006103515625, "watchLater": false}
```

As you can see after stopping playback at **19:18:16.914**, the Kodi refresh happens at **19:18:18.010** and access resumepoints at **19:18:18.098**, whereas we update resumepoints at **19:18:18.490** So we come 400ms too late for Kodi to pick up our information.

Lowering loop sleep from 500 to 50, does not impact this either. Kodi is always faster to refresh the container then we are with updating resumepoints.

The best option for us is to refresh the resumepoints internally (we need the assetPath or uuid for this) and avoid rereading the cache in this case. It would be nice if we could detect from the call if this is Kodi refreshing or not.

**Comment by dagwieers** [comment]
Superseeded by #555

**Pull request closed without merging**
