### PR TITLE
Move cursor down when ListItem is unfollowed/removed

### PR DESCRIPTION
**Pull request by dagwieers**
This fixes an annoying issue where your cursor would jump to the start of
the list when you unfollow a program in the favorite listing, and so the
selected ListItem disappears from under the cursor.

This also implements a smarter way to know where we are within the
add-on at any time.

This requires tamland/kodi-plugin-routing#20

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Interesting "hack", but isn't moving up a better way?

When you remove the last item, you will end on the previous item instead, what will be the next last item.

Not sure what happens now when you are on the last or the first item. Does it loop?

**Comment by dagwieers** [comment]
@michaelarnauts There are two corner-cases (1) you are on the last item (2) the next item is also remove as part of unfollowing a program. In both cases you will jump to the top, and there's not a lot we can do about it. But at least we have fix 90% of the cases with this.

**Comment by dagwieers** [comment]
Still waiting for the [routing PR](https://github.com/tamland/kodi-plugin-routing/pull/20) to be accepted and released.

**Comment by dagwieers** [comment]
The fix for routing (tamland/kodi-plugin-routing#20) has been released.
So this is ready to be merged.

**Pull request merged**
