### PR TITLE
Prepare for v2.3.1 release

### PR DESCRIPTION
**Pull request by dagwieers**
Update README and addon.xml for release.

### CODE REVIEW

**Comment by dagwieers** [comment]
I would like to release this ASAP. I have had a few more reports of people not being able to start VRT NU since the v2.3.0 update. Going into the settings solves it, but not everyone may realize this.

**Comment by dagwieers** [comment]
@mediaminister Can I release the current master branch?

**Comment by dagwieers** [comment]
Since recently the scraping fails again for the categories listing.
```
======================================================================
FAIL: test_get_categories (test.test_webscraper.TestWebScraper)
Test to ensure our hardcoded categories conforms to scraped categories
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dag/home-made/plugin.video.vrt.nu/test/test_webscraper.py", line 21, in test_get_categories
    self.assertEqual(categories_scraped, categories_stored)
AssertionError: Lists differ: [{'name': u'', 'id': u'met-aud... != [{'name': u'Audiodescriptie', ...

First differing element 0:
{'name': u'', 'id': u'met-audiodescriptie'}
{'name': u'Audiodescriptie', 'id': u'met-audiodescriptie'}

Diff is 2285 characters long. Set self.maxDiff to None to see it.
```

**Comment by mediaminister** [comment]
Fixed in https://github.com/pietje666/plugin.video.vrt.nu/pull/677

**Pull request merged**
