### PR TITLE
Support credentials through environment

### PR DESCRIPTION
**Pull request by dagwieers**
This will allow us to do testing using actual credentials on Travis.
This can improve coverage.

### CODE REVIEW

**Comment by dagwieers** [comment]
@pietje666 Can you add a VRTNU_USERNAME and VRTNU_PASSWORD environment variable in Travis? As described here: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

You can flag them as being "not to be shared" so that they do not end up in the Travis output.

**Comment by dagwieers** [comment]
Going to merge this for testing.

**Comment by pietje666** [comment]
was just going to do it

**Comment by dagwieers** [comment]
No longer needed ;-)

**Pull request merged**
