### PR TITLE
Differentiate between Label and Title

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Clear distinction between Label and Title
- Add `get_title()` metadata function
- Add `get_mediatype()` metadata function
- Set proper mediatype for oneoff videos
- Add FIXMEs for a known label/title issue in Kodi/Estuary

### CODE REVIEW

**Comment by dagwieers** [comment]
@mediaminister We seem to have issues with web scraping. Maybe changes to the VRT NU website ?

**Comment by mediaminister** [comment]
Indeed, the livestream player is removed from the channel pages of Eén en Canvas (https://www.vrt.be/vrtnu/kanalen/een/ https://www.vrt.be/vrtnu/kanalen/canvas/)
I still have to investigate the impact on the add-on, I expect there could be a problem watching Eén and Canvas live from the TV guide menu.
I'll provide a fix as soon as possible.

**Comment by dagwieers** [comment]
A few remarks:
- This PR without a change to Kodi has no real impact (except maybe code clarity)
- Using `sorttitle` does not seem to have any effect on sorting

**Comment by mediaminister** [comment]
@dagwieers I think the problem you are trying to fix is situated here: https://github.com/pietje666/plugin.video.vrt.nu/blob/07619e8a5c877b6d7d237d76203c910c23245ec8/resources/lib/apihelper.py#L236

**Comment by dagwieers** [comment]
Oh damn :scream:

**Comment by mediaminister** [comment]
I found the cause, `xbmcplugin.addSortMethod` is messing things up.

**Comment by dagwieers** [comment]
> I found the cause, xbmcplugin.addSortMethod is messing things up.

Yes, I can reproduce this now. Thanks, it would have taken me some time to find this :roll_eyes:

**Comment by dagwieers** [comment]
So this PR works as expected but with any sort methods... :disappointed:

**Comment by dagwieers** [comment]
The current PR is ready to be merged, but doesn't fix the original issue I intended to fix. But at least we understand better what is going on and where the fix is needed. I added 2 FIXMEs in the code to highlight this.

**Comment by dagwieers** [comment]
Going to merge this as it adds various small visual improvements. We can improve on this later (especially if we want to improve oneoffs wrt. #670).

**Pull request merged**
