### PR TITLE
Include LICENSE and README.md in release

### PR DESCRIPTION
**Pull request by dagwieers**
So next release will be easier ;-)

### CODE REVIEW

**Comment by dagwieers** [comment]
No windows ;-)

**Comment by dagwieers** [comment]
If we merge #102 this is actually no longer needed.

**Comment by pietje666** [comment]
> No windows ;-)

No windows needed!  Although it would have crashed at the Process.Start (that's why i removed it in the PR). Actually first i was making a self contained binary but it was 70 mb for a packager.

https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/runtime-2.1.2

**Comment by dagwieers** [comment]
Don't take this the wrong way, but creating a zip file is just a simple command.
Running make is so much easier, and available on almost every Linux system.

I know the Microsoft world is adopting Linux at a fast pace, and I have been doing Powershell stuff the past few years (for Ansible), but I like to keep simple things simple, and for me that excludes using .Net core for creating ZIP files. Sorry :-)

**Comment by pietje666** [comment]
I understand but i am bad at scripting!

**Pull request merged**
