### PR TITLE
Prepare for v2.2.0 release

### PR DESCRIPTION
**Pull request by dagwieers**
Update README and addon.xml for release.

### CODE REVIEW

**Comment by mediaminister** [comment]
One problem: addon.xml is limited to 1500 characters

**Comment by dagwieers** [comment]
Only for the add-on that is in the official Kodi repository. And honestly I don't understand why only 1500 characters.

I prefer to have a bit more version information in the plugin we offer through GitHub, because we can ;-) I think starting from v2.0.0 is ok for that.

**Comment by mediaminister** [comment]
No problems found during testing. It's okay for me to release.

**Comment by dagwieers** [comment]
Would you mind if I also added proper breadcrumbs in our addon?
https://github.com/michaelarnauts/plugin.video.vtm.go/pull/46#issuecomment-520821911

I noticed the Netflix add-on is doing it, and it really looks nice if a listing has a proper indication of what the listing is about.

**Comment by mediaminister** [comment]
Go ahead.

**Comment by dagwieers** [comment]
So I implemented #436, it's not perfect but already quite useful.
And we can make it perfect in v2.2.1, or v2.3.0 (whichever comes first).

I will prepare a v2.2.0 release tomorrow if you approve.

**Comment by mediaminister** [comment]
Approved.

**Comment by dagwieers** [comment]
> One problem: addon.xml is limited to 1500 characters

I decided to remove the authors from the contributions in the addon.xml changelog.
This way we can retain the v2.0.0 changelog.

In the future I will continue doing it like this for the addon.xml, but keep it as-is in the README.md if you agree.

**Comment by mediaminister** [comment]
I agree.

Unfortunately, there is a another issue since this night:
I think Widevine DRM stopped working in inputstream.adaptive. I don't know the impact yet, but it looks very bad:
https://forum.kodi.tv/showthread.php?tid=339798&pid=2877192#pid2877192
Can you confirm that the livestream doesn't start with "Use Widevine DRM" enabled?

**Comment by dagwieers** [comment]
Correct, all live streams fail (except VRT NWS and the Radio streams).
I guess we have to make an issue for this so we can channel user requests there.

**Comment by mediaminister** [comment]
I'll make an issue.

**Comment by dagwieers** [comment]
Apparently CDM 14.4 or newer is needed: https://www.widevine.com/news

**Pull request merged**
