### PR TITLE
allow Kodi to select lower bandwidth hls streams

### PR DESCRIPTION
**Pull request by mediaminister**
A first simple fix for https://github.com/pietje666/plugin.video.vrt.nu/issues/172

### CODE REVIEW

**Comment by dagwieers** [comment]
I would prefer to delay this until after the v1.9.0 release (this weekend ?).
And maybe even until it's a bit more full-featured?

If we keep this branch in sync with the master branch, people that need it can use this branch.
This reminds me to look into automatic repository with versions from branches so people can enable this in Kodi for testing. This would be ideal for things like this we want to experiment with. Or to get fixes out to people faster.

**Comment by mediaminister** [comment]
This pull request repairs Kodi's own video quality selection function in case the user has set a bandwidth limitation, but this only works with HLS streams. I'm still investigating but it seems inputstream.adaptive has a similar bandwidth setting.

So, I doubt this will become a full feature in our add-on. A proper fix definitely need adjustments upstream.

**Comment by dagwieers** [comment]
@mediaminister I don't really understand how this PR works. I think I miss some context on how things now work. I am also not sure if this is still useful if #189 works as expected.

**Comment by mediaminister** [comment]
I'll explain. When inputstream.adaptive with Widevine DRM-support is not available (for example in Kodi 17), we need to use the HLS-streams VRT (still) provides. HLS-streams work directly in Kodi player.

But, as Kodi player is relatively slow to select a HLS substream, I wrote the `_select_hls_substreams ` function to always select the highest quality HLS-substream and send that stream directly to Kodi player. This speeds up video playback.
The `_select_hls_substreams ` function also contains a workaround to provide webvtt subtitles for video on demand items, because Kodi player doesn't handle this right.

This pull request basicly adds an` 'if else'` structure to the `_select_hls_substreams ` function so when the user has set a bandwith limit, the function does nothing.

Maybe this pull request isn't usefull anymore, I'll look into this at a later time when I have more time.

You should know that some workarounds are needed in a Kodi 17/ HLS-streaming context:
- webvtt subtitling
- faster video playback

**Comment by dagwieers** [comment]
@mediaminister Ok, that clears it up. One thing I wondered was why we only specify **inputstream.adaptive** for DASH streams and not HLS. But I guess that's because we make that selection ourselves. Could we maybe add some additional notes/comments to the code for this ? Like explicitly mention Kodi 17 for specific workarounds.

So am I right that for Kodi 18 we don't have any specific workarounds ? Or should we report something upstream to get it fixed properly there ?

Also, why don't we set inputstream.adaptive for HLS streams in a Kodi 18 context ?

**Comment by dagwieers** [comment]
It is also clear I need my own Kodi 17 setup for testing...

**Comment by dagwieers** [comment]
> But, as Kodi player is relatively slow to select a HLS substream

How slow is relatively slow ?

I noticed that playing a stream is already relatively slow. I haven't found a way to speed it up. For my VRT Radio plugin I did notice that playing stream directly, rather than another ListItem round-trip does help (but obviously requires Kodi to handle everything correctly from the start and no additional handling required).

**Comment by mediaminister** [comment]
@dagwieers We have to take a lot into account when selecting the streams:
- subtitles, audio and video should always work on any Kodi platform
- enabling DRM is a free user choice
- inputstream.adaptive and/or DRM doesn't work in earlier Kodi versions
- Kodi player doesn't support fragmented WebVTT subtitling in HLS and doesn't support MPEG-DASH at all.

And now we have to take into account that bandwidth is also a free user choice, so it gets more complicated.

Not using inputstream.adaptive for HLS is a choice to keep `streamservice` as simple as possible. It means we use the HLS and subtitling workaround also on Kodi 18. So we limit combinations of al these different factors and make sure subtitling always works. The workarounds are not only related to Kodi versions but also to the DRM user setting or to inputstream.adaptive.

> Could we maybe add some additional notes/comments to the code for this ?
Good idea, I'll do this when I find the time.

> Or should we report something upstream to get it fixed properly there ?
Not sure yet what we need, I'll first look at your fix.

> Also, why don't we set inputstream.adaptive for HLS streams in a Kodi 18 context ?
I didn't test the VRT HLS streams, so I'm unsure if subtitling works well.

> How slow is relatively slow ?
When I tested last year, my substream selection workaround saved one or two seconds.

**Comment by dagwieers** [comment]
> - inputstream.adaptive and/or DRM doesn't work in earlier Kodi versions

At the moment I don't think we support anything other than v17 (Krypton) and v18 (Leia).

> - Kodi player doesn't support fragmented WebVTT subtitling in HLS and doesn't support MPEG-DASH at all.

Ok, but inputstream.adaptive does support HLS and MPEG-DASH, right ? It's only fragmented WebVTT subtitling in HLS that is broken ? If so, let's open an issue upstream and track it. We can then refer to this upstream ticket in the workaround code.

I don't mind the workarounds at all (even if I wasn't aware of it all) but if we can report/fix stuff upstream we can slowly get rid of the extra code over time.

Another thing I would like to fix is that our code includes logging (Info|Verbose|Debug) so that it becomes more clear that when something does not work correctly, we know exactly what the code is doing and the user has a more informed guess at what could be the problem. I already added this to the settings, we now have to expose this to our log-functions and add sufficient entries.

I hope with more information I can determine why I have never seen 720p streams working. And I don't know if it's because they are not available, or I have an issue on my system.

**Pull request merged**
