### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Add unit tests to pylint
- Fix unit tests (even if they don't work as-is yet)
- Run streamserviceests.py as part of unit tests (not by Travis)

### CODE REVIEW

**Comment by dagwieers** [comment]
@mediaminister @pietje666 Approved ?

**Comment by mediaminister** [comment]
No! I get an error: `ImportError: No module named resources.lib.kodiwrappers`

**Comment by dagwieers** [comment]
Ok, I fixed that.

**Comment by pietje666** [comment]
Code wise it looks good :)

**Comment by mediaminister** [comment]
I still get the same error. `ImportError: No module named resources.lib.kodiwrappers`

**Comment by dagwieers** [comment]
@mediaminister Yup, this will require the same modifications as #187, so I think I am going to split off the unit test fixes, and drop this in favor of #187, which already has the required modifications (but not using the same path).

**Pull request merged**
