### PR TITLE
Attempt to use json.load(fd) again

### LINKED ISSUE #554: No json object could be decoded
### Describe the bug ###
After playing another video (spoed 24/7), I again got the below traceback. This is the second time in two days to get this exact error. The first time I added it to #385 

### Additional context ###
- Operating system: LibreELEC 9.2 Beta1 (9.1.501)
- Kodi version: 18.4
- Addon version: 2.3.0 branch
- Using a VPN: no
- Country you are using the addon from: BE

### Log (if available) ###
```
2019-10-28 23:32:00.392 T:1937471936  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-28 23:32:00.392 T:1937471936  NOTICE: VideoPlayer: finished waiting
2019-10-28 23:32:00.392 T:1937471936  NOTICE: CVideoPlayer::CloseFile()
2019-10-28 23:32:00.392 T:1937471936  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-28 23:32:00.392 T:1937471936  NOTICE: VideoPlayer: finished waiting
2019-10-28 23:32:00.432 T:1937471936   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-10-28 23:32:00.492 T:1220756352  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 2833.000244140625, 'total': 2833.000244140625, 'event': u'playbackended'}
2019-10-28 23:32:00.503 T:1220756352  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-648cfa46-c891-43c0-8043-3a59d443687e&size=1
2019-10-28 23:32:01.778 T:1506800512  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-10-28 23:32:01.869 T:1220756352  NOTICE: [plugin.video.vrt.nu] Cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn' deleted
2019-10-28 23:32:01.880 T:1220756352  NOTICE: [plugin.video.vrt.nu] Delete file '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'.
2019-10-28 23:32:01.947 T:1220756352  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginrt.tkn'
2019-10-28 23:32:01.950 T:1220756352  NOTICE: [plugin.video.vrt.nu] URL get: https://token.vrt.be/refreshtoken
2019-10-28 23:32:02.002 T:1506800512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_plugin.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 301, in run
                                                plugin.run(argv)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 98, in favorites_recent
                                                VRTPlayer(kodi).show_recent_menu(page=page, use_favorites=True)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 243, in show_recent_menu
                                                self._favorites.refresh(ttl=5 * 60 if use_favorites else 60 * 60)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/favorites.py", line 37, in refresh
                                                xvrttoken = TokenResolver(self._kodi).get_xvrttoken(token_variant='user')
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 71, in get_xvrttoken
                                                token = self._get_cached_token('X-VRT-Token', token_variant)
                                              File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/tokenresolver.py", line 100, in _get_cached_token
                                                token = json.load(fdesc)
                                              File "/usr/lib/python2.7/json/__init__.py", line 291, in load
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2019-10-28 23:32:02.259 T:1245934464   ERROR: GetDirectory - Error getting plugin://plugin.video.vrt.nu/favorites/recent
2019-10-28 23:32:02.264 T:1937471936   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/favorites/recent) failed
```

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Add abstraction layer for http requests
- Add abstraction layer for decoding json
- Use json.load(fd) again
- Early exit in tokenresolver
- Rename statichelper.py to utils.py
- Selective imports
- Small code improvements

This fixes #554
This relates to #385

### CODE REVIEW

**Comment by dagwieers** [comment]
I moved the non-Kodi-specific stuff (which was caching-related) to utils.py.
I would like to move the non-VRT-related stuff from statichelpers to utils.py as well.
And maybe rename statichelpers.py (with VRT-related stuff) to vrtutils.py ?

**Comment by mediaminister** [comment]
> And maybe rename statichelpers.py (with VRT-related stuff) to vrtutils.py ?

I'm okay with rearranging functionality in different utils files.

I got the following error with https://github.com/pietje666/plugin.video.vrt.nu/pull/624/commits/85d065a3d5a18312eabe4314bd096daa4c72f04a on Python 3:
```
2019-12-09 13:53:18.659 T:8092   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'NameError'>
                                            Error Contents: name 'ValueError' is not defined
                                            Traceback (most recent call last):
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon_entry.py", line 14, in <module>
                                                run(argv)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon.py", line 299, in run
                                                plugin.run(argv)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\addon.py", line 151, in programs
                                                VRTPlayer().show_episodes_menu(program=program, season=season)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\vrtplayer.py", line 244, in show_episodes_menu
                                                self._resumepoints.refresh(ttl=ttl('indirect'))
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\resumepoints.py", line 37, in refresh
                                                resumepoints_json = get_cache('resume_points.json', ttl)
                                              File "C:\Users\test\AppData\Roaming\Kodi\addons\plugin.video.vrt.nu\resources\lib\utils.py", line 60, in get_cache
                                                return load(fdesc)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 296, in load
                                                parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 348, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 353, in raw_decode
                                                obj, end = self.scan_once(s, idx)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 35, in __init__
                                                ValueError.__init__(self, errmsg)
                                            NameError: name 'ValueError' is not defined
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
I don't think so, `ValueError` should exist.
https://docs.python.org/3/library/exceptions.html#ValueError

I cannot split it up as I envisioned because of circular dependencies.
I now have statichelpers.py renamed to vrtutils.py (which is mostly ok, except for from_unicode and to_unicode)

**Comment by dagwieers** [comment]
> I don't think so, ValueError should exist.

The integration tests did not fail for this, so it ought to work. What Python version is this?

**Comment by dagwieers** [comment]
The error does not make sense and is not something we can do anything about anyway.
JSONDecodeError is subclassed from ValueError, if ValueError would not be defined, it could not subclass from it.

I wonder if you have somewhere old .pyc files lying around that may be redefining ValueError, or something like that. If you distribute using ZIP files that can't happen, but if you copy over files, you may accidentally leave being .pyc or .pyo or __pycache__ files.

```python
class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    lineno: The line corresponding to pos
    colno: The column corresponding to pos

    """
    # Note that this exception is used from _json
    def __init__(self, msg, doc, pos):
        lineno = doc.count('\n', 0, pos) + 1
        colno = pos - doc.rfind('\n', 0, pos)
        errmsg = '%s: line %d column %d (char %d)' % (msg, lineno, colno, pos)
        ValueError.__init__(self, errmsg)
        self.msg = msg
        self.doc = doc
        self.pos = pos
        self.lineno = lineno
        self.colno = colno

    def __reduce__(self):
        return self.__class__, (self.msg, self.doc, self.pos)
```

**Comment by mediaminister** [comment]
I got this error with the built-in Python 3 in  Kodi 19.0-ALPHA1 Git:20191205-b238c23acc for Windows x64

**Comment by mediaminister** [comment]
I got the same error again on a clean Kodi install: 19.0-ALPHA1 Git:20191209-923cfade46
Full debug log: [fulldebug.txt](https://github.com/pietje666/plugin.video.vrt.nu/files/3939915/fulldebug.txt)

**Comment by dagwieers** [comment]
What python version is this? We test almost the entire codebase (including these routines) against 3.5, 3.6, 3.7 and 3.8.

Could you copy the above definition of the JSONDecodeError class from this Python here ?
I would expect it to be identical and subclassing from ValueError.

I would say that Python is severely broken. It is contradicting itself, which is only possible if ValueError was somehow deleted during operation (`del __builtins__.ValueError`).

I get the same error if I do:
```python
#!/usr/bin/python
del __builtins__.ValueError
import json
```

Causing this:
```bash
[dag@moria plugin.video.vrt.nu]$ python test.py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import json
  File "/usr/lib64/python2.7/json/__init__.py", line 109, in <module>
    from .encoder import JSONEncoder
  File "/usr/lib64/python2.7/json/encoder.py", line 275, in <module>
    ValueError=ValueError,
NameError: name 'ValueError' is not defined
```

**Comment by dagwieers** [comment]
Or an even better example:
```python
#!/usr/bin/python

import json
del __builtins__.ValueError
raise json.JSONDecodeError(doc='', msg='', pos=3)
```
results in:
```bash
[dag@moria plugin.video.vrt.nu]$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    raise json.JSONDecodeError(doc='', msg='', pos=3)
  File "/usr/lib64/python3.6/json/decoder.py", line 35, in __init__
    ValueError.__init__(self, errmsg)
NameError: name 'ValueError' is not defined
```

**Comment by mediaminister** [comment]
> What python version is this?
It should be Python 3.7 (https://github.com/xbmc/xbmc/commit/61f40eaf0863e5508db0419adaae014309a53e0a)

```python
class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    lineno: The line corresponding to pos
    colno: The column corresponding to pos

    """
    # Note that this exception is used from _json
    def __init__(self, msg, doc, pos):
        lineno = doc.count('\n', 0, pos) + 1
        colno = pos - doc.rfind('\n', 0, pos)
        errmsg = '%s: line %d column %d (char %d)' % (msg, lineno, colno, pos)
        ValueError.__init__(self, errmsg)
        self.msg = msg
        self.doc = doc
        self.pos = pos
        self.lineno = lineno
        self.colno = colno

    def __reduce__(self):
        return self.__class__, (self.msg, self.doc, self.pos)
```

**Comment by dagwieers** [comment]
So I think this is ready to be merged.
The reported `NameError` seems to me something that either should happen to older VRT NU releases as well, or is related to the distribution mechanism distributing compiled objects onto a newly installed system. (BTW Even if you reinstall Kodi, the userdata directories may not be cleaned up).

**Comment by mediaminister** [comment]
You can merge this as this is an improvement and doesn't break things.

> Even if you reinstall Kodi, the userdata directories may not be cleaned up

Userdata was definitely removed, I reconfigured VRT NU add-on, activated debug logging again, etc...it really was a clean Kodi install.

I suspect the `ValueError` happens when `xbmcvfs` is doing multiple disk operations at the same time.

I can reproduce this error when starting and stopping episodes quickly after each other.

**Comment by dagwieers** [comment]
@mediaminister Ok, I believe you. Then the less probable cause is a bug (or at least an incompatibility) in the Python version of Kodi 19 related to `reuselanguageinvoker`. Either a design fault triggered by a newer Python 3, or an actual bug that can be fixed.

A minimal reproducer will probably convince developers, but if you report this I expect disbelieve and expecting a user-problem (like me :-)). It would explain why we do not see this in our integration tests.

What could also help, is recursively grepping the code for "ValueError" (and anything causing it to become undefined briefly when e.g. reloading something).

**Comment by dagwieers** [comment]
PS I doubt this is `xbmcvfs` related, it is more related to the inner workings of Python or how `reuselanguageinvoker` works.

**Comment by dagwieers** [comment]
I tried to reproduce this on a Windows 10 laptop using Kodi 19.0-ALPHA1 Git_20191018 and I couldn't reproduce the reported issue, but I managed to make Kodi crash after 7 successive playbacks of Terzake episodes :roll_eyes: 

Now going to upgrade to test again.

**Comment by dagwieers** [comment]
@mediaminister I cannot reproduce this with Kodi 19.0-ALPHA1 64bit Git_20191209, can you provide more detailed instructions?

**Comment by mediaminister** [comment]
Steps to reproduce:

1) Open a menu of a program with multiple episodes.

2)  Alternately play two different episodes for the shortest time possible
- Play episode 1 until you have video
- Stop Player
- Play episode 2 until you have video
- Stop Player

Repeat the steps in 2) until you get an error.

**Comment by dagwieers** [comment]
Would probably be the easiest to disable `reuselanguageinvoker` and see if it can still be reproduced.

**Comment by dagwieers** [comment]
> Steps to reproduce:

I tried that a lot. But ending video playback usually takes a second or more, so it's hard to actually play them with little delay. Maybe it is easier using the JSONRPC interface?

**Comment by dagwieers** [comment]
I cannot reproduce this. The fastest way to play streams is by adding a folder to the playlist (press Q on a folder, e.g. TerZake) and then you can select new video's without having to leave the listing.

**Comment by mediaminister** [comment]
Okay, nevermind, I just tested this in Virtualbox, I'll open an issue if I can reliably reproduce this on another Windows system.

**Pull request merged**
