### PR TITLE
Implement inputstream.adaptive.max_bandwidth

### LINKED ISSUE #172: Lower quality stream/ ISP limits
### Describe the bug ###

Might not be a bug with the addon...

Situation: went over download budget with ISP.
Download speed is now limited to ~100kB/s

Videostream from addon play for 2 sec, then buffers, then plays 2 sec.
Clearly the restricted bandwidth is playing a role here.
! no fault of the addon.

However VRT website does something different. When playing livestream
or using on demand it switches to a lower quality stream.
Playback then functions normal (no more buffer empty) at a lower quality.

I do not know, maybe the addon can implement something similar if it notices
the bandwidth is not sufficient?
A sort of auto fallback?

Greetings:

ps @dagwiers: Your EPG is great. MUCH better to use with the Kodi
remote.

### PR DESCRIPTION
**Pull request by dagwieers**
Attempt to use max_bandwidth for inputstream.adaptive.

This will select the lowest value of both the global network max_bandwidth as well as our own max_bandwidth setting.

This fixes #172

### CODE REVIEW

**Comment by dagwieers** [comment]
This does not work as I expected. The settings do not show the pull-down menu as the main settings page. And whatever value inserted does not appear to work.

**Comment by mediaminister** [comment]
Thanks, this can work for `mpeg_dash` streams. Just check if inputstream.adaptive is enabled, DRM is enabled and check if you're using integers in the `get_max_bandwidth` function.

**Comment by dagwieers** [comment]
@mediaminister I am not sure if this is related to DRM only. AFAICT it works for **inputstream.adaptive** in general. In fact, I think it's even better to always add this property so it also works if somehow Kodi decides to use **inputstream.adaptive**.

**Comment by dagwieers** [comment]
And I am now also setting **network.bandwidth** for every stream, and it simply works.

So with this PR we successfully limit the bandwidth on all the streams. The only thing not limited is our own HTTP requests, and I am not sure if we really have to. Maybe we ought to provide a drop-down list of values like the global setting.

PS It now no longer belongs to the **DRM** settings tab, so again where do we put this ? I think we have to reduce **Credentials**, **Subtitles**, **DRM**, **Advanced** into **Credentials**, **Interface**, **Video** and then move Subtitles and DRM to **Video**.

**Comment by mediaminister** [comment]
For now, it definitely doesn't work for hls streams, because these streams are handled by `_select_hls_substreams` function which always selects the highest quality stream before sending the url to Kodi player.

**Comment by dagwieers** [comment]
@mediaminister I understand now. Our best hope for the future is to have both HLS and DASH be handled by Kodi itself. In the meantime we have to handle bandwidth limitation ourselves as best as we can for HLS.

So I'll merge both PRs, and change the settings in a follow-up PR.

**Comment by mediaminister** [comment]
> And I am now also setting network.bandwidth for every stream, and it simply works.
@dagwieers Are you sure this really works, for example when you disable DRM and play a livestream?

**Comment by dagwieers** [comment]
@mediaminister I will test. Using **network.bandwidth** did work for a scenario where **inputstream.adaptive.max_bandwidth** did not work though. But it would help if the logs would indicate which scenario I am effectively testing (now I simply try a few things that I assume are different scenarios, but can't know for sure...)

For debugging, we may want to force MPEG-DASH or HSL ourselves, maybe ? Maybe a new option in settings ?

**Comment by dagwieers** [comment]
And maybe we should Mock ListItem so we can actually test if we get the expected ListItem entries for each of the scenarios based on settings/bandwidth.

**Comment by mediaminister** [comment]
Disable the DRM user setting and play Eén or Canvas livestream and you get always HLS. The streaming protocol is already displayed in the log. I don't think we need other settings.

**Comment by dagwieers** [comment]
Wait until you see the implementation I have in my head... :-)
(Not sure if everything is possible though, but would be neat!)

**Comment by dagwieers** [comment]
@mediaminister I can confirm that "network.bandwidth" does not work. So it means for streams played by Kodi/HLS, only the global setting takes effect. So probably the best way forward is to remove the bandwidth setting from our plugin, and only take the global setting into account. Unless we specify that this setting only affects *true* inputstream.adaptive-induced streams.

**Comment by dagwieers** [comment]
I finally found why 720p HD streams were not working. By default InputStream Adaptive has a configuration setting **Ignore Display Resolution** which is disabled. I guess since my display resolution is 1080p, which could not be matched, it did not select 720p.

I updated our documentation, and add a [HD quality](https://github.com/pietje666/plugin.video.vrt.nu/wiki/HD-quality) section.

**Pull request merged**
