### PR TITLE
faster stream selection

### PR DESCRIPTION
**Pull request by mediaminister**
I edited UrlToStreamService class to provide the stream urls faster. For compatibility with older Kodi installations without inputstream.adaptive or DRM-support, the highest quality HLS-variant is directly provided cause the standard Kodi-player is fairly slow to select the HLS-variants.

So, inputstream.adaptive or DRM isn't necessarily required.

### CODE REVIEW

**Comment by pietje666** [comment]
pushed a new version to the kodi repo with all your changes. Btw how do you test if your code is working right now? + Do you have a background in developing mediastreams or something?

**Comment by dagwieers** [comment]
All working fine. 720p on live streams, w00t w00t !
And subtitles is working fine as well.

Is it possible to get higher resolution content for on-demand watching too ?

**Comment by pietje666** [comment]
So right now you create a Zip, manually install it in Kodi for testing? There are also Unit test classes available which might make your life easier when testing :).

**Comment by mediaminister** [comment]
No, I created a symbolic link between the Kodi addon folder and the plugin-folder in my local git repository. You don't need a zip, Kodi just executes what's in the addon folder.
Testing Kodi in different Virtualbox environments is more fun for me than writing unit test classes.

**Pull request merged**
