### PR TITLE
Clean url router

### PR DESCRIPTION
**Pull request by mediaminister**
This implements the new router design as discussed in https://github.com/pietje666/plugin.video.vrt.nu/issues/103

### CODE REVIEW

**Comment by dagwieers** [comment]
Oh god, I broke it really good. Need to think about how to add `refresh` in this new scheme.

**Comment by dagwieers** [comment]
Let me offer a fix for this the coming week.
I think we can use the existing scheme and merge it with the CACHES database as it was implemented. I just need to add `@plugin.router()` entries for most of what is in **vrtplayer.py** and add my own for the refresh-part. (Trying to combine `refresh` with the existing logic is way to invasive, so I am not going to try that  with the new scheme).

**Comment by mediaminister** [comment]
> Oh god, I broke it really good. 
I think i fixed it. Don't overcomplicate things.

**Comment by dagwieers** [comment]
Well, I don't like the fact that we have an interface now for removing arbitrary files.
So let's merge this and then see how we can improve things.

**Comment by dagwieers** [comment]
And thanks for fixing this. The quick succession of changes really speeds up development.

**Comment by mediaminister** [comment]
Thanks for merging, now we can move forward with the new interface.
The cache refresh could surely be improved. For instance a container refresh doesn't refresh the tvguide caching file.

**Comment by dagwieers** [comment]
@mediaminister I am rewriting using the routing module now and it is even looking more fabulous :-)
Hope I can test this in an hour and share it here.

**Pull request merged**
