### PR TITLE
Add Radio 2 and events live stream

### PR DESCRIPTION
**Pull request by dagwieers**
It appears Radio 2 works as well using a vualto-radio2 id, and we can
also add Radio 1.

### CODE REVIEW

**Comment by mediaminister** [comment]
It seems `vualto_radio1` stream is starting much slower than `vualto_events3_geo`. I should still investigate why.

**Comment by dagwieers** [comment]
I noticed that as well, and it was the reason for not merging it right away. I wanted to test this on another device first.

**Comment by dagwieers** [comment]
I had not seen the errors before, so 415 is Unsupported Media Type again?

**Comment by mediaminister** [comment]
Yes,  Unsupported Media Type, there must be something wrong with this stream. I tried playing the stream https://live-radio-cf.lwc.vrtcdn.be/groupa/live/d6fdec5d-5d67-4cc3-9f8c-e3e8993c8ee4/live.isml/.mpd with https://www.jwplayer.com/developers/stream-tester/ and I also got an error.

**Comment by dagwieers** [comment]
Sure, let's keep this open for now.

**Comment by dagwieers** [comment]
# [Codecov](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=h1) Report
> Merging [#685](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=desc) into [master](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/commit/8cfd4f781e73abaf4afd51b62e18fae1db109d80&el=desc) will **decrease** coverage by `7.25%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #685      +/-   ##
==========================================
- Coverage   83.17%   75.92%   -7.26%     
==========================================
  Files          40       40              
  Lines        4956     4859      -97     
==========================================
- Hits         4122     3689     -433     
- Misses        834     1170     +336     
```


| [Impacted Files](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [test/test\_resumepoints.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-dGVzdC90ZXN0X3Jlc3VtZXBvaW50cy5weQ==) | `59.25% <0.00%> (-38.99%)` | :arrow_down: |
| [resources/lib/tokenresolver.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi90b2tlbnJlc29sdmVyLnB5) | `56.00% <0.00%> (-33.73%)` | :arrow_down: |
| [resources/lib/favorites.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi9mYXZvcml0ZXMucHk=) | `56.84% <0.00%> (-27.54%)` | :arrow_down: |
| [resources/lib/resumepoints.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi9yZXN1bWVwb2ludHMucHk=) | `64.33% <0.00%> (-23.95%)` | :arrow_down: |
| [test/test\_favorites.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-dGVzdC90ZXN0X2Zhdm9yaXRlcy5weQ==) | `60.27% <0.00%> (-17.36%)` | :arrow_down: |
| [resources/lib/metadata.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi9tZXRhZGF0YS5weQ==) | `65.90% <0.00%> (-16.10%)` | :arrow_down: |
| [resources/lib/playerinfo.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi9wbGF5ZXJpbmZvLnB5) | `17.61% <0.00%> (-11.95%)` | :arrow_down: |
| [resources/lib/service.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-cmVzb3VyY2VzL2xpYi9zZXJ2aWNlLnB5) | `55.31% <0.00%> (-10.64%)` | :arrow_down: |
| [test/xbmcgui.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-dGVzdC94Ym1jZ3VpLnB5) | `57.50% <0.00%> (-9.90%)` | :arrow_down: |
| [test/test\_streamservice.py](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree#diff-dGVzdC90ZXN0X3N0cmVhbXNlcnZpY2UucHk=) | `79.77% <0.00%> (-8.14%)` | :arrow_down: |
| ... and [16 more](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=footer). Last update [8cfd4f7...9396a11](https://codecov.io/gh/pietje666/plugin.video.vrt.nu/pull/685?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by dagwieers** [comment]
I reported this issue to VRT, let's see what they say about it.

**Comment by dagwieers** [comment]
I am going to merge this as this adds the extra Events streams (which includes the rugby match between Belgium and Spain on Events 2 stream)

**Comment by dagwieers** [comment]
The web scraper seems broken again. I am going to merge this and hopefully look at the webscraper this evening.

**Comment by mediaminister** [comment]
There were just two more problems with unit tests. Fixed in https://github.com/xbmc/xbmc/pull/17435

**Comment by dagwieers** [comment]
Since the VRT Events 3 stream no longer carries the Radio 1 live stream, I tried a third attempt at contacting VRT to report the HTTP 415 Unsupported Media Type error using https://www.vrt.be/nl/heb-je-een-vraag/

I will create a PR to make **vualto_radio1** the default stream for Radio 1 live stream, even when it starts to play with an 11 seconds daly :disappointed:

**Pull request merged**
