### PR TITLE
Re-initialize addon when settings change

### PR DESCRIPTION
**Pull request by mediaminister**
This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/560

### CODE REVIEW

**Comment by dagwieers** [comment]
Does this work?

Because both are running in two different 'languageinvokers' (python instances) I would assume. And each has a different process id, or am I wrong?

**Comment by mediaminister** [comment]
I tested and it works. Approved by Team Kodi: https://forum.kodi.tv/showthread.php?tid=290353&pid=2425543#pid2425543

**Comment by dagwieers** [comment]
It does not seem to work for me though.
If I open you addon in the Main menu, then go to settings and disable "Enable My favorites", then I would expect the Main menu to not show "My favorites", but it does.
Even restarting the add-on does not work, you have to load another add-on and then go back to VRT NU to ensure the new settings are updated.

**Comment by dagwieers** [comment]
If this was possible, it would mean the service, and the addon would be in the same process space using the same module cache. And then the service could update addon objects, and vice versa.

But that is not possible, the only way service and addon can communicate is through Kodi itself (i.e. Player object, or Window properties, or notifications). Otherwise we wouldn't have had so many issues with Playerinfo and getting information across.

**Comment by mediaminister** [comment]
I noticed strange behaviour. The first and second time it doesn't seem to work, but from the third time it works.

**Comment by dagwieers** [comment]
I have had my share of strange behavior putting me on the wrong foot many times with Kodi.
(Combinations of reuselanguageinvoker, old service process and brainfarts)

But at least the PID of the addon and the service appear to be the same:
```
2019-11-30 01:58:17.738 T:1305473920  NOTICE: [plugin.video.vrt.nu] Service started (PID=648)
2019-11-30 01:58:20.570 T:1247798144  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/
2019-11-30 01:58:20.570 T:1247798144  NOTICE: [plugin.video.vrt.nu] PID = 648
```

So one assumption out the window already ;-) But restarting the add-on does not change the PID.
This PID however is the PID of the main **kodi.bin**, so I think this is because it is multi-threaded and the service and addon live in a different thread.

**Comment by dagwieers** [comment]
> I noticed strange behaviour. The first and second time it doesn't seem to work, but from the third time it works.

It never works for me, can you give me a walkthrough how to see it work?

**Comment by dagwieers** [comment]
I am open to improve #608 with something that doesn't update ADDON on every invocation. But at least this is slightly better than disabling `reuselanguageinvoker`.

All-in-all, I think this is something that Kodi should fix. Not us.

**Comment by mediaminister** [comment]
> It never works for me, can you give me a walkthrough how to see it work?

It worked when you changes "Enable My favorites" three times in a row. (Three times opening and closing addon settings.)

But nevermind, it's fixed now in master branch.

**Comment by dagwieers** [comment]
I did try that. It could be useful to understand such a mechanism, because it could be useful for other uses as well.

**Pull request closed without merging**
