### PR TITLE
Improvements to PlayerInfo

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- ~Add onPlayBackSeek, onThreadExit and onPlayBackStarted event handlers~ #597 
- ~Asynchronous resumepoints updates~ #595 
- ~Implement window properties functions~ #597 
- ~Store Container.URL in Window properties~ #597 
- Add unique ids to ListItem objects
- ~Simplify Service class and improve PlayerInfo class~ #597

~The onPlayBackSeek and onPlayBackStarted events are required so seeking and the initial start (from beginning) would update to correct timing. If not, quitting immediately after playing or after seeking would not get registered (as the position would not have updated).~
    
~The asynchronous resumepoint update is useful because currently updating resumepoints is a blocking call and could interfere with normal operations (i.e. when having network issues).~
    
~In all other cases updating favorites or resumepoints is already asynchronous because they are initiated by a context menu.~

### CODE REVIEW

**Comment by dagwieers** [comment]
@mediaminister I have attempted 2 things yesterday evening (this PR is not representative, as unfinished):
- Use `onThreadExit` (when the main position loop exits) to update position to avoid Container.Refresh
- Use Window properties to store additional playing information to avoid another lookup before pushing resumepoints

The first item seems to work, but because the lookup takes too long, may not always be in time for Kodi's refresh. So if we can avoid the additional lookup (item 2) then I think this would work out fine.

**Comment by mediaminister** [comment]
> Use Window properties to store additional playing information to avoid another lookup before pushing resumepoints

You mean that we need to store the `uuid`, `title` and `url` in a Listitem and pass it to a window property when the Listitem got selected?
I tried this already but I can only get information from a selected Listitem with Infolabels: https://kodi.wiki/view/InfoLabels
In theory we could use the `Listitem` ` UniqueID`, as it accepts dictionaries with our own custom keys, but it seems there is no Infolabel to get this data back.

**Comment by dagwieers** [comment]
I still need to look at this again as I noticed the VRT NU add-on is quite slow in refreshing the Favourites listings, especially when a video has ended.

It takes about 12 seconds or more:
```
2019-11-22 02:56:25.474 T:1251992448  NOTICE: thread end: video_thread
2019-11-22 02:56:25.540 T:1304425344  NOTICE: Closing stream player 3
2019-11-22 02:56:25.686 T:1936735664  NOTICE: CVideoPlayer::CloseFile()
2019-11-22 02:56:25.687 T:1936735664  NOTICE: VideoPlayer: waiting for threads to exit
2019-11-22 02:56:25.688 T:1936735664  NOTICE: VideoPlayer: finished waiting
2019-11-22 02:56:25.688 T:1936735664  NOTICE: CVideoPlayer::CloseFile()
2019-11-22 02:56:25.688 T:1936735664  NOTICE: VideoPlayer: waiting for threads to exit
2019-11-22 02:56:25.688 T:1936735664  NOTICE: VideoPlayer: finished waiting
2019-11-22 02:56:25.702 T:1152377728  NOTICE: [plugin.video.vrt.nu] [PlayerInfo] 4433 stream position loop exited
2019-11-22 02:56:25.729 T:1579713408  NOTICE: [plugin.video.vrt.nu] [Notification] sender=xbmc, method=VideoLibrary.OnUpdate, data={"id":-1,"type":"episode"}
2019-11-22 02:56:25.741 T:1936735664   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-11-22 02:56:26.572 T:1579713408  NOTICE: [plugin.video.vrt.nu] [Notification] sender=xbmc, method=Player.OnStop, data={"end":true,"item":{"episode":222,"season":2019,"showtitle":"Terzake","title":"[B]Terzake[/B] - 'Terzake' van donderdag 21 november[COLOR yellow]ᵛ[/COLOR]","type":"episode"}}
2019-11-22 02:56:26.674 T:1579713408  NOTICE: [plugin.video.vrt.nu] [PlayerInfo] 4433 onPlayBackEnded
2019-11-22 02:56:27.275 T:1579713408  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 1850.0001220703125, 'total': 1850.0001220703125, 'event': u'playbackended', 'path': 'plugin://plugin.video.vrt.nu/play/id/vid-4b565447-411b-4009-8e6f-0422502c0698/pbs-pub-85403db8-153a-44cf-807f-033d2ba7de17'}
2019-11-22 02:56:27.454 T:1579713408  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-4b565447-411b-4009-8e6f-0422502c0698&size=1
2019-11-22 02:56:27.517 T:1251992448  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-11-22 02:56:27.731 T:1251992448  NOTICE: [plugin.video.vrt.nu] Cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn' deleted
2019-11-22 02:56:27.739 T:1251992448  NOTICE: [plugin.video.vrt.nu] Delete file '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'.
2019-11-22 02:56:27.751 T:1251992448  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginrt.tkn'
2019-11-22 02:56:27.762 T:1251992448  NOTICE: [plugin.video.vrt.nu] URL get: https://token.vrt.be/refreshtoken
2019-11-22 02:56:27.947 T:1579713408  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginrt.tkn'
2019-11-22 02:56:27.962 T:1579713408  NOTICE: [plugin.video.vrt.nu] URL get: https://token.vrt.be/refreshtoken
2019-11-22 02:56:28.387 T:1251992448  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/favorites
2019-11-22 02:56:28.600 T:1579713408  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-22 02:56:28.857 T:1251992448  NOTICE: [plugin.video.vrt.nu] Write cache 'favorites.json'.
2019-11-22 02:56:29.102 T:1579713408  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-22 02:56:29.249 T:1251992448  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 5 minutes and 0 seconds.
2019-11-22 02:56:29.268 T:1251992448  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-22 02:56:29.276 T:1251992448  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-22 02:56:29.597 T:1579713408  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-22 02:56:29.605 T:1579713408  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points/contentdamvrt20191114terzake20191121dodepotwp00148180
2019-11-22 02:56:29.614 T:1579713408  NOTICE: [plugin.video.vrt.nu] URL post data:: {"url": "/vrtnu/a-z/terzake/2019/terzake-d20191121/", "position": 1850.0001220703125, "total": 1850.0001220703125, "whatsonId": "0", "watchLater": false}
2019-11-22 02:56:29.734 T:1251992448  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-22 02:56:30.454 T:1251992448  NOTICE: Previous line repeats 1 times.
2019-11-22 02:56:30.454 T:1251992448  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 27 minutes and 35 seconds.
2019-11-22 02:56:30.463 T:1579713408  NOTICE: [plugin.video.vrt.nu] [PlayerPosition] resumepoint update Terzake 20191121 plugin://plugin.video.vrt.nu/favorites/recent
2019-11-22 02:56:30.669 T:1579713408  NOTICE: [plugin.video.vrt.nu] [PlayerPosition] update container plugin://plugin.video.vrt.nu/favorites/recent
2019-11-22 02:56:30.763 T:1579713408  NOTICE: [plugin.video.vrt.nu] Execute: Container.Update(plugin://plugin.video.vrt.nu/favorites/recent)
2019-11-22 02:56:31.138 T:1251992448  NOTICE: [plugin.video.vrt.nu] [Metadata] manual resumetime set to 934
2019-11-22 02:56:31.513 T:1152377728  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-11-22 02:56:32.104 T:1152377728  NOTICE: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 4 minutes and 58 seconds.
2019-11-22 02:56:32.946 T:1152377728  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 4 minutes and 58 seconds.
2019-11-22 02:56:34.046 T:1152377728  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-22 02:56:34.334 T:1152377728  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-22 02:56:37.287 T:1152377728  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-22 02:56:37.679 T:1152377728  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 27 minutes and 28 seconds.
2019-11-22 02:56:43.087 T:1152377728 WARNING: Attempt to use invalid handle 19
```

**Comment by dagwieers** [comment]
> You mean that we need to store the uuid, title and url in a Listitem and pass it to a window property when the Listitem got selected?

No, the idea is to store information in Window 10000 so we don't have write it to disk, or retrieve it online. There are even add-ons like Netflix who use Window 10000 for caching everything (for as long as the add-on window is available).

**Comment by dagwieers** [comment]
Same thing happened today:
```
2019-11-23 00:28:10.010 T:1505751936  NOTICE: Closing stream player 1
2019-11-23 00:28:10.012 T:1505751936  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
2019-11-23 00:28:10.028 T:1210221440  NOTICE: thread end: OMXPlayerAudio::OnExit()
2019-11-23 00:28:10.111 T:1505751936  NOTICE: Closing stream player 2
2019-11-23 00:28:10.112 T:1505751936  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
2019-11-23 00:28:10.113 T:1227006848   ERROR: OMXPlayerVideo: Got MSGQ_IS_ERROR(-1) Aborting
2019-11-23 00:28:10.113 T:1227006848  NOTICE: thread end: video_thread
2019-11-23 00:28:10.266 T:1937268144  NOTICE: CVideoPlayer::CloseFile()
2019-11-23 00:28:10.266 T:1937268144  NOTICE: VideoPlayer: waiting for threads to exit
2019-11-23 00:28:10.266 T:1937268144  NOTICE: VideoPlayer: finished waiting
2019-11-23 00:28:10.267 T:1937268144  NOTICE: CVideoPlayer::CloseFile()
2019-11-23 00:28:10.267 T:1937268144  NOTICE: VideoPlayer: waiting for threads to exit
2019-11-23 00:28:10.267 T:1937268144  NOTICE: VideoPlayer: finished waiting
2019-11-23 00:28:10.281 T:1563362176  NOTICE: [plugin.video.vrt.nu] [Notification] sender=xbmc, method=VideoLibrary.OnUpdate, data={"id":-1,"type":"episode"}
2019-11-23 00:28:10.299 T:1563362176  NOTICE: [plugin.video.vrt.nu] [Notification] sender=xbmc, method=Player.OnStop, data={"end":true,"item":{"episode":32,"season":2019,"showtitle":"De afspraak op vrijdag","title":"[B]De afspraak op vrijdag[/B] - Hoe zit het met de ethische kwesties die het parlement wil behandelen?[COLOR yellow]ᵛ[/COLOR]","type":"episode"}}
2019-11-23 00:28:10.311 T:1937268144   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-11-23 00:28:10.540 T:1563362176  NOTICE: [plugin.video.vrt.nu] [PlayerInfo] 6895 onPlayBackEnded
2019-11-23 00:28:10.541 T:1278731136  NOTICE: [plugin.video.vrt.nu] [PlayerInfo] 6895 stream position loop exited
2019-11-23 00:28:10.601 T:1563362176  NOTICE: [plugin.video.vrt.nu] Got VRT NU Player info: {'position': 2637.000244140625, 'total': 2637.000244140625, 'event': u'playbackended', 'path': 'plugin://plugin.video.vrt.nu/play/id/vid-06c43787-3dfb-41f7-974f-9c477327c033/pbs-pub-6775a1a8-c88c-4759-b863-ad8a0eeb1a48'}
2019-11-23 00:28:11.347 T:1563362176  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[videoId]=vid-06c43787-3dfb-41f7-974f-9c477327c033&size=1
2019-11-23 00:28:11.350 T:1210221440  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-11-23 00:28:11.605 T:1210221440  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-23 00:28:11.616 T:1210221440  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/favorites
2019-11-23 00:28:11.796 T:1563362176  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-23 00:28:11.805 T:1563362176  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-23 00:28:12.088 T:1210221440  NOTICE: [plugin.video.vrt.nu] Write cache 'favorites.json'.
2019-11-23 00:28:12.452 T:1563362176  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-23 00:28:12.850 T:1210221440  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 5 minutes and 0 seconds.
2019-11-23 00:28:12.879 T:1210221440  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-23 00:28:12.888 T:1210221440  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-23 00:28:13.091 T:1563362176  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-23 00:28:13.099 T:1563362176  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points/contentdamvrt20191122deafspraakopvrijdag20191122vrdepotwp00163183
2019-11-23 00:28:13.107 T:1563362176  NOTICE: [plugin.video.vrt.nu] URL post data:: {"url": "/vrtnu/a-z/de-afspraak-op-vrijdag/2019/de-afspraak-op-vrijdag-d20191122/", "position": 2637.000244140625, "total": 2637.000244140625, "whatsonId": "0", "watchLater": false}
2019-11-23 00:28:13.317 T:1210221440  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-23 00:28:14.052 T:1563362176  NOTICE: Previous line repeats 1 times.
2019-11-23 00:28:14.052 T:1563362176  NOTICE: [plugin.video.vrt.nu] [PlayerPosition] resumepoint update De afspraak op vrijdag 20191122 plugin://plugin.video.vrt.nu/favorites/recent
2019-11-23 00:28:14.060 T:1210221440  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 4 minutes and 18 seconds.
2019-11-23 00:28:14.068 T:1563362176  NOTICE: [plugin.video.vrt.nu] [PlayerPosition] update container plugin://plugin.video.vrt.nu/favorites/recent
2019-11-23 00:28:14.076 T:1563362176  NOTICE: [plugin.video.vrt.nu] Execute: Container.Update(plugin://plugin.video.vrt.nu/favorites/recent)
2019-11-23 00:28:14.619 T:1210221440  NOTICE: [plugin.video.vrt.nu] [Metadata] manual resumetime set to 1855
2019-11-23 00:28:15.020 T:1302328192  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites/recent
2019-11-23 00:28:16.443 T:1302328192  NOTICE: [plugin.video.vrt.nu] Cache 'favorites.json' is fresh, expires in 4 minutes and 57 seconds.
2019-11-23 00:28:17.136 T:1302328192  NOTICE: [plugin.video.vrt.nu] Cache 'resume_points.json' is fresh, expires in 4 minutes and 57 seconds.
2019-11-23 00:28:18.225 T:1302328192  NOTICE: [plugin.video.vrt.nu] Got cached token '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/user_XVRTToken.tkn'
2019-11-23 00:28:18.236 T:1302328192  NOTICE: [plugin.video.vrt.nu] URL post: https://video-user-data.vrt.be/resume_points
2019-11-23 00:28:20.732 T:1302328192  NOTICE: [plugin.video.vrt.nu] Write cache 'resume_points.json'.
2019-11-23 00:28:20.954 T:1596932992   ERROR: Window Translator: Can't find window infodialog
2019-11-23 00:28:21.342 T:1302328192  NOTICE: [plugin.video.vrt.nu] Cache 'my-recent-1.json' is fresh, expires in 4 minutes and 11 seconds.
```
Summarizing, when this item was played:
- We perform **one time** an update to favorites
- We perform **three times** a forced refresh to resumepoints
- We access cached token user_XVRTToken.tkn **five times**

**Comment by dagwieers** [comment]
I think this implementation is working, but it may require some review ;-)

**Comment by mediaminister** [comment]
> I think this implementation is working, but it may require some review ;-)

I shortly tested and it seems resumepoints are not updated from Kodi to VRT NU.

**Comment by mediaminister** [comment]
It seems window properties don't work as expected:
```
2019-11-23 13:44:28.000 T:139771025049344  NOTICE: [plugin.video.vrt.nu] [PlayerPosition] title= asset_id= (onThreadExit)
```

**Comment by dagwieers** [comment]
Hmm, I haven't seen that. Let me clean up this PR and remove the name-changes and other unrelated "fixes".

**Comment by dagwieers** [comment]
Ok, I found one issue that explains why it worked for me in my repetitive testing on the same content :-( And I also still need to perform a container refresh in this PR.

I modified the logic for storing and getting the container url using window properties. But I would like to understand why window properties do not appear to work for you.

**Comment by dagwieers** [comment]
Aha, it seems to work again the way I have seen this work.
No container refresh (because our refresh is requested before the container is refreshed by Kodi).

Please test and review this.

**Comment by mediaminister** [comment]
@dagwieers I checked and window properties are never set when using the normal `plugin://plugin.video.vrt.nu/play/id/` interface because there is no video metadata passed to the `kodiutils` play function.

Your window properties approach needs an extra lookup in VRT NU api for each item that is played, but this slows down the start of the playback.

The extra lookup (`apihelper get_single_episode`) is implemented for the `airdate`, `latest` and `upnext` interfaces so this explains why the window properties work in some cases.

**Comment by mediaminister** [comment]
I added a commit that fixes resumepoints functionality without using "window properties".

**Comment by dagwieers** [comment]
If we cannot move this stuff out of service.py, make playerinfo.py perform what is needed (without additional lookups for things we already now) and start a playerinfo thread only when VRT NU is playing something, this PR has no merit IMO

The aim was to make things more efficient so that the Kodi refresh would pick up changes automatically and not need another container refresh.

I guess the async resumepoints update has some merit, I will open another PR for that if you agree.

**Comment by mediaminister** [comment]
I agree to make a new PR, moving the lookup for `asset_id`, `title` and `url`  out of `push_position` is also an improvement.

**Comment by dagwieers** [comment]
@mediaminister I just realized I just destroyed your commit when rebasing. So beware !

**Comment by mediaminister** [comment]
> However, I still think we should only get this information once and store it somewhere (and the Windows properties are to me the best place for this kind of caching).

I'm not in favor of doing this. This means you need to store window properties for every single video item before you store this data in Kodi GUI Listitems.

**Comment by dagwieers** [comment]
> I'm not in favor of doing this. This means you need to store window properties for every single video item before you store the video metadata in Kodi GUI Listitems.

Possibly, we will see.

It mostly depends on the order of magnitude of a persistent storage over caching (disk) or network lookups, and the complexity of the code. Ideally we only have to write the selected item, or can perform a lookup on the existing listing. Two things I haven't tried.

The easiest solution would be to improve Kodi, but we haven't been very successful on that front in the past :-/ If only Kodi was written in Python ;-)

**Comment by dagwieers** [comment]
@mediaminister With the speed improvements and not using Window properties, this PR lives up to its expectations again. It responds very fast on interaction and does not require a container refresh.

Not sure if the unique ids have any merit, so I can ditch that as well. But the PlayerInfo changes seem to help.

**Comment by mediaminister** [comment]
Everything that is not functional should be removed before we can merge this:
- unused window properties
- unused unique id functionality

I also experienced that this branch doesn't reliable mark episodes as watched while playing "Up Next" episodes.

**Comment by dagwieers** [comment]
All the important and working parts have been merged to #613 and subsequently merged.

**Pull request closed without merging**
