### PR TITLE
Remove entries from resume_points

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Simplify overrule_kodi_watched logic
- Implement deleting resumepoint entries
- Add logic for finding entries being watched

### CODE REVIEW

**Comment by dagwieers** [comment]
I also have a script to clean this up:
```python
#/usr/bin/python
import sys
import json

sys.path.append('resources/lib')
sys.path.append('test')

from xbmcaddon import Addon
from tokenresolver import TokenResolver
from resumepoints import ResumePoints
try:  # Python 3
    from urllib.request import urlopen, Request
except ImportError:  # Python 2
    from urllib2 import urlopen, Request

#ADDON = Addon()
#ADDON.setSetting('username', 'USERNAME')
#ADDON.setSetting('password', 'PASSWORD')

_resumepoints = ResumePoints()
_resumepoints.refresh(ttl=0)

xvrttoken = TokenResolver().get_xvrttoken(token_variant='user')
headers = {
    'authorization': 'Bearer ' + xvrttoken,
    'content-type': 'application/json',
    'Referer': 'https://www.vrt.be/vrtnu',
}

for key, value in _resumepoints._data.items():
    value = value.get('value')

    # If already deleted, continue
    if value is None:
        continue

    # If is being watched later, skip
    if value.get('watchLater') == True:
        continue

    # If position within normal playing window
    if 30 < value.get('position') < value.get('total') * 92 / 100:
        continue

    # Delete
    url = 'https://video-user-data.vrt.be/resume_points/%s' % key
    req = Request(url, headers=headers)
    req.get_method = lambda: 'DELETE'
    result = urlopen(req)
    print('%s -- %s' % (key, result.getcode()))
```

**Comment by mediaminister** [comment]
While quitting Player after using "Up Next" I got an error.
```
2019-12-14 15:22:13.683 T:140039858140928  NOTICE: [plugin.video.vrt.nu] Removed '{asset_id}' from resumepoints
2019-12-14 15:22:13.684 T:140039858140928   ERROR: Exception in thread StreamPosition:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/test/.kodi/addons/plugin.video.vrt.nu/resources/lib/playerinfo.py", line 154, in stream_position
                                                self.onThreadExit()
                                              File "/home/test/.kodi/addons/plugin.video.vrt.nu/resources/lib/playerinfo.py", line 146, in onThreadExit
                                                self.push_position(position=self.last_pos, total=self.total)
                                              File "/home/test/.kodi/addons/plugin.video.vrt.nu/resources/lib/playerinfo.py", line 220, in push_position
                                                asynchronous=True
                                              File "/home/test/.kodi/addons/plugin.video.vrt.nu/resources/lib/resumepoints.py", line 78, in update
                                                return self.delete(asset_id)
                                              File "/home/test/.kodi/addons/plugin.video.vrt.nu/resources/lib/resumepoints.py", line 168, in delete
                                                del self._data[asset_id]
                                            KeyError: u'contentdamvrt20191128deidealewereld2019nja0026depotwp00159949'
```

**Comment by mediaminister** [comment]
Watch status is not updated anymore when using "Up Next".

**Comment by dagwieers** [comment]
Is watch status broken because of this PR? Or in general?

**Comment by mediaminister** [comment]
> Is watch status broken because of this PR? Or in general?

Not sure yet, I also experienced a similar problem with the master branch. I'll test more today and try to fix it.

**Comment by mediaminister** [comment]
I think I caught all bugs in this PR now. I'm going to merge this.

As resumepoints are now deleted when an episode is completely watched, I didn't find a solution yet to mark "Up Next" episodes as watched.

**Comment by dagwieers** [comment]
@mediaminister I am afraid this needs to be fixed in Kodi :disappointed: There is only so much we can work around before things fall over. (I personally think we are stretching this too far already, and this is biting us already for the upcoming delayed release :cry:)

**Pull request merged**
