### PR TITLE
Add 'De Warmste Week' channel

### PR DESCRIPTION
**Pull request by mediaminister**

### CODE REVIEW

**Comment by dagwieers** [comment]
I don't mind adding this, but what do we do the rest of the year with this channel?
IIRC there are a handful of other VRT related Youtube channels that we did not add.
Maybe we ought to add **More VRT YouTube channels** at the end of the channels-list?

**Comment by mediaminister** [comment]
I added this because there is a 'De Warmste Week' channel with video content on VRT NU website and this broke `test_tvshows` in `test_apihelper.py`

**Comment by dagwieers** [comment]
The other YouTube channels are:
- VRT (https://www.youtube.com/channel/UCojJNXcer3yKj9Q-RWOFZuw)
- VRT NU (https://www.youtube.com/channel/UCt3RWMlMKf5jKg5cvqxC_xA)
- Terzake (https://www.youtube.com/user/terzaketv)
- Ketnet Musical (https://www.youtube.com/channel/UCB90ZMfqVLgGtp3Z99h4GWg)
- Karrewiet (https://www.youtube.com/channel/UCCUHHJrtsoC1oyihO86mnMg)

**Comment by mediaminister** [comment]
Feel free to make a new pull request for this, but this is currently not a priority for me.

**Pull request merged**
