### PR TITLE
Allow to disable VRT NU credentials

### PR DESCRIPTION
**Pull request by dagwieers**
Probably not worth it.

My idea was to disable all functionality that required credentials (i.e. giving up anonymity).

### CODE REVIEW

**Comment by pietje666** [comment]
What can people do when they do not use credentials? And i do wonder if there is a demand for that?

**Comment by mediaminister** [comment]
You can watch the livestreams, that's all.
This pull request is useless. There is no real demand for this, in fact we are all forced to create login credentials to use VRT NU.

**Comment by dagwieers** [comment]
Well, in this case only the live streams could work without credentials.
But other content like Radio and Youtube channels could work as well.

**Comment by mediaminister** [comment]
We definitely don't need a user setting for something that works perfectly without.

**Comment by dagwieers** [comment]
The main reason for contemplating this was the need to add something in the first settings-screen that doesn't catch the cursor. Currently if you go into settings, you can't go back to the tabs easily because your cursor is caught in the text-form. With a keyboard or remote control it sucks.

So the only thing we can do is add something before the text input. A slide to turn credentials on/off made the most sense, since another annoying issue is the fact that you end up in the settings/credentials if it was set to empty (even if this was on purpose).

So the slide formalizes the wish to not enter credentials. Yet, you can still browse the catalogue, TV guide or play live streams... Catching 2 birds with one stone.

**Pull request closed without merging**
