### PR TITLE
add method to play a program given a channel and airdate

### PR DESCRIPTION
**Pull request by mediaminister**

### CODE REVIEW

**Comment by michaelarnauts** [comment]
@mediaminister you made a valid point in the issue regarding the different start times in different guides. I've replied here https://github.com/pietje666/plugin.video.vrt.nu/issues/367#issuecomment-508987131 that we maybe also should include the end time to best match a show.

**Comment by dagwieers** [comment]
Matching the mean between start and end with the timeframe of broadcasts seems the most safe?
In fact we could support both, if only start is provided vs if both are provided.

**Comment by michaelarnauts** [comment]
I'm not sure if it is possible to get the end time, so in that case the solution of @mediaminister seems to be the best choice.

**Comment by mediaminister** [comment]
We can indeed support both, end date can be optional and this doesn't have to break the current implementation.

**Comment by mediaminister** [comment]
Support for end_date is added.

**Comment by dagwieers** [comment]
@michaelarnauts Can you test ?

@mediaminister When this is ready, please remove the WIP from the subject :-)

**Comment by mediaminister** [comment]
It's not yet completely ready  but it works. Other improvements will be added at a later time.

**Comment by dagwieers** [comment]
I need to know if this will go into v2.1.0 or not. I don't mind to add new functionality that may have issues (or could be improved). Especially since it is niche functionality. But what do you want?

**Comment by mediaminister** [comment]
You can add this already to 2.1.0, no problem.

**Pull request merged**
