### PR TITLE
Replace kodiwrapper with kodiutils

### LINKED ISSUE #560: Changes to settings do not take effect immediately
### Describe the bug ###
Most of the changes to the settings require you to restart the add-on (which means first starting another add-on, then return to VRT NU). This is not very user-friendly (i.e. most people would think restarting the add-on would do the trick).

So it's safe to say that people would consider this a bug (changing settings doesn't have any effect). And especially for logging this is problematic, if you enable debug-logging in Kodi, our add-on wouldn't act on it.

We need to address this before releasing v2.3.0.

### To Reproduce ###
1. Change logging settings
2. Continue using the add-on
3. Or restart the add-on
4. Logging changes do not have any effect

### Expected behavior ###
We need to rethink this. Either reevaluate config-options on use (slower) or reevaluate settings when changes are detected.

### Additional context ###
- Operating system: LibreELEC 9.2 Beta2 (9.1.502)
- Kodi version: 18.4
- Addon version: 2.3.0 (devel branch)
- Using a VPN: no
- Country you are using the addon from: BE

### PR DESCRIPTION
**Pull request by dagwieers**
This is an attempt to simplify the addon.

This PR includes:
- Removing the KodiWrapper class in favor of discrete functions (kodiutils)
- Rename some kodiutils functions to shorter variants
- Selective imports from kodiutils and json
- Make more use of `has_addon()`
- Remove unused code (resumepoints/favorites invalidate_caches)
- Instantiate Addon() every time, don't cache it (this fixes #560)

This fixes #560

### CODE REVIEW

**Comment by dagwieers** [comment]
From **plugin.video.mediathekview**:
```python
    def reload_settings(self):
        """ Reload settings and reconfigure service behaviour """
        # self.info("===== RELOAD SETTINGS =====")
        # TODO: support online reconfiguration
        #       currently there is a bug in Kodi: this event is only
        #       triggered if the reconfiguration happen inside the
        #       addon (via setSetting). If teh user changes something
        #       via the settings page, NOTHING WILL HAPPEN!
        pass
```

**Comment by mediaminister** [comment]
I just did a quick test and I can confirm this fixes #560.
You can merge this already, I will test the master branch later this weekend.

**Comment by dagwieers** [comment]
Do you agree with the removal of KodiWrapper as well ?

**Comment by mediaminister** [comment]
Yes, I totally agree with removing KodiWrapper. I think simplifying the addon structure is very much needed.

**Pull request merged**
