### PR TITLE
Prepare for v2.2.3 release

### PR DESCRIPTION
**Pull request by dagwieers**
Update README and addon.xml for release.

### CODE REVIEW

**Comment by dagwieers** [comment]
There is no real urgency to release, and no real bug-fixes, just minor improvements.
I don't think we need a major release for this.

**Comment by dagwieers** [comment]
However I would like so see the issues related text formatting in Kore (#249) and Chorus (#361) fixed.

**Comment by mediaminister** [comment]
If we mention support for unicode Windows profile paths, we should also make a release for inputstreamhelper because 0.4.2 doesn't support this yet.

**Comment by dagwieers** [comment]
@mediaminister Good point. I think we are indeed ready to also make a release for **inputstreamhelper**, but that is more your department ;-)

**Pull request merged**
