### PR TITLE
Reorganize settings

### PR DESCRIPTION
**Pull request by dagwieers**
This PR implements:
- **Credentials**
  - Username
  - Password
- **Video**
  - Show subtitles
  - Use DRM
  - ~Internet bandwidth limitation~
- **Interface**
  - Permalink in plot
- ~**VRT Radio**~
  - ~Install/run VRT Radio~
- **Debug**
  - Inputstream Adaptive settings
  - Clear VRT cookies
  - Log level

### CODE REVIEW

**Comment by mediaminister** [comment]
VRT Radio and Debug is useless, everyone who wants to enable these settings or add-ons, can do this in Kodi.
We don't need to duplicate functionality, keep it simple please.

**Comment by dagwieers** [comment]
@mediaminister The Radio section is to make it easier to find VRT Radio, and I plan to do the same in the VRT Radio plugin. But only if it can both install it (if needed) and run it. (Currently it only runs it).

For **Debug** I do think it is useful to have this readily available. And both Retrospect as well as Netflix plugin are doing the same. The Log level only affects the plugin log settings, which I think is an important property as well. Kodi's debug logging is too verbose.

**Comment by mediaminister** [comment]
1) You can easily find and install other add-ons through Kodi's search function. I thought we agreed to make this a separate project because VRT NU is a video service.
2) Debug is okay for me, but I think most users will never use this the debug option.

**Comment by dagwieers** [comment]
Things I would like to see in the future as well:
- Parental
  - Exclusive channel list (limit everything based on channel list)
  - Day/Time settings (only enable plugin between specific times)
- **Debug**
  - (Re-)install Widevine
  - Clear tokens
  - Force stream selection (MPEG-DASH/HLS/...) *(This may report failure if it is not possible)*

**Comment by dagwieers** [comment]
@mediaminister VRT Radio *is* a separate project, but I think it is in the user's best interest as well as beneficial to both projects to link to each other as they are both complementary. There are other more plugins that do similar things.

@pietje666 What do you think ? If you both object obviously I won't do it, but this is what I would propose.

**Comment by dagwieers** [comment]
In the longer run I was even thinking to link to other plugins that relate to Flemish (or even Belgian) TV stations. Have a **More...** tab with Retrospect Belgium, Yelo, and others. But that would be an even more controversial idea ;-)

**Pull request merged**
