### PR TITLE
Add an action to check your credentials from the add-on settings.

### LINKED ISSUE #351: Allow checking credentials from an action in the settings xml
When configuring the addon, but you are not sure what your credentials are. The current flow is as follows:
* Go to settings and fill in your username and password.
* Save
* Open addon, go to A-Z, select a program and try to play it.
* An error occurs, start again.

We can use the `action` type in the settings xml to run an action that checks the credentials, and show a message if it failed or was successful.

I'm willing to create a PR for this, as an attempt to get to know the codebase a bit :)

### PR DESCRIPTION
**Pull request by michaelarnauts**
Fixes #351 

This adds a function to `tokenresolver.py` to just check the tokens. I couldn't reuse an existing function since they look in cache first. The credentials tab in the settings has an action now to run this function that checks the login credentials. A message is displayed indicating success or failure, and the settings dialog is shown again.

Note that I had to add `option="close"` to the settings since Kodi only saves the settings when the dialog is closed.

I also added `*.pyo` to the `.gitignore` file. Kodi creates these compiled files.

### CODE REVIEW

**Comment by dagwieers** [comment]
I would like to postpone this to v2.0.1 or v2.1.0 (whatever comes first).

**Comment by mediaminister** [comment]
Should definitely postponed because https://github.com/pietje666/plugin.video.vrt.nu/issues/351 is maybe not fully valid.

**Comment by michaelarnauts** [comment]
Sure, I wasn't aiming at the 2.0 release

**Comment by dagwieers** [comment]
I tested it yesterday and it works fine.

I am even inclined to remove the automatic clearing of the password when authentication fails. It would also be nice if there was an option to show the password (even if temporarily).

**Comment by dagwieers** [comment]
So will the next version be v2.0.1 or v2.1.0 ? :-)
We are running out of ideas to implement...

**Comment by michaelarnauts** [comment]
@dagwieers, i would prefer if the password won't reset. I had a typo in my username and it was a bit strange that my password was cleared :)

**Comment by dagwieers** [comment]
@michaelarnauts Exactly my point :-) Do you want to make a PR for this?

**Pull request merged**
