### PR TITLE
WIP: Reorganize structure and design

### LINKED ISSUE #103: Move to using script.module.routing
**Describe the bug**
Yesterday I stumbled on **plugin.video.fosdem** and I was charmed by how simple and easy the code was to understand. Now I am convinced we ought to be using **script.module.routing** as well (I added it to the refactoring roadmap).

See https://github.com/jelly/plugin.video.fosdem/blob/master/addon.py#L56

More information related to **script.module.routing**: 
- Documentation: https://github.com/tamland/kodi-plugin-routing
- Tutorial: https://github.com/afrase/kodiswift/blob/master/docs/tutorial.rst

### PR DESCRIPTION
**Pull request by dagwieers**
Things I would like to do:
- Use a routing library for having a more simple interface
- Rename overly long functions, e.g. get_localized_string()
- Move all python files into a single directory

**This is a work-in-progress.**

This fixes #103 and #176

### CODE REVIEW

**Comment by dagwieers** [comment]
One big problem with **script.module.routing** is that URLs (or anything with slashes) cannot be passed through. Another problem is that the global **plugin** object needs to be passed on as well, while I had hoped that this would not be needed. So it's an even more radical change than I had hoped.

I have some working code for some of the menu listings, but it requires a lot more work. Feel free to discuss any design changes in the current PR, because there's a lot going on.

**Comment by mediaminister** [comment]
I don't like script.module.routing, I think a separate navigation function is good enough. For instance: https://github.com/mediaminister/plugin.video.vrt.nu/blob/fast/resources/lib/vrtnu/vrtnu.py#L24

**Comment by dagwieers** [comment]
So my approach for this will be to reorganize everything except the existing routing, so that existing paths do not break. However, I think we need to redesign that part at some point as well. But we can go to great length without affecting this for now.

**Comment by dagwieers** [comment]
Some of this will happen in another PR, some day.

**Pull request closed without merging**
