### PR TITLE
Re-add option to disable favorites

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Re-added the settings option to enable/disable favorites
- Only enable My programs when settings enable it and credentials are detected
- Reorganize unit tests (move from vrtplayer to apihelper)

This is done over concerns from https://github.com/pietje666/plugin.video.vrt.nu/pull/213#issuecomment-492657267

Additionally, I think we need to add help to individual settings to give a little bit more insight into how settings affect the VRT NU addon. This also gives more maturity to our addon settings pages...

### CODE REVIEW

**Comment by dagwieers** [comment]
@mediaminister Does this help with your concerns, provided we add help information in the Settings.

**Comment by dagwieers** [comment]
It appears that help messages don't work for addon settings, this is something for my list of Kodi shortcomings :-(

**Comment by mediaminister** [comment]
Are you sure this works on a fresh Kodi installation? I can't use "my programs" on a fresh install.

My main concern is that a new function shouldn't slow down or break the basic functionality of the add-on (for new users):
These are my considerations:
- instantly showing the main menu
- livestreaming without login
- asking login, downloading user data only when needed and when the user initiates this request through a listitem (or setting).
- caching after the first user interaction, not before.

**Comment by dagwieers** [comment]
@mediaminister If you do not have any credentials, the "My programs" will not appear. As soon as you enter your credentials (and have it enabled in the settings) that menu item should become visible. This is basically what you requested. People can now use the live streams and work as before without credentials.

All your considerations are met with this implementation, and it worked fine for me. I now also tested on Windows and discovered an issue with expirationDate when using Dutch Kodi locale (on an English Windows). I have a fix for this.

**Comment by mediaminister** [comment]
Thanks for the explanation. It works now after providing credentials.
And many thanks for taking into account my concerns.

**Comment by dagwieers** [comment]
I appreciate your feedback and help too ! :-)

**Pull request merged**
