### PR TITLE
Prepare for v2.3.0 release

### PR DESCRIPTION
**Pull request by dagwieers**
Update README and addon.xml for release.

### CODE REVIEW

**Comment by dagwieers** [comment]
IMO there is still a long way to go, but I would like to get more people to test this upcoming release. And we need a branch for this to get users to a zip file. So I will keep this branch in sync with the master branch.

**Comment by dagwieers** [comment]
@mediaminister It appears that Kodi trims whitespaces from the start of the description/news fields, but doesn't do so for each consecutive line, only from the beginning and end of the string. That means that an indented payload in XML will become incorrectly indented in the Add-on information pane :-/

**Comment by mediaminister** [comment]
Okay, I see.

**Comment by mediaminister** [comment]
FYI, for "Up Next" to work with VRT NU add-on, you need at least Up Next version 1.0.2 which is not available in Kodi repo right now. The best option would be to make a new Up Next release first.

**Comment by dagwieers** [comment]
@mediaminister What exactly do we need from Up Next v1.0.2 ?

**Comment by mediaminister** [comment]
> What exactly do we need from Up Next v1.0.2 ?

I didn't investigated it yet, but while testing on Windows I found out that Up Next 1.0.1 doesn't play the next episode with Kodi 19 nightly.
I found no problems with 1.0.1 on Kodi 18.4

**Comment by mediaminister** [comment]
I meanwhile investigated this and I found out Up Next needs a new release to support Python3 in Kodi 19. With older versions, there are different errors related to Python3.

I was mistaken that we only need 1.0.2, we really need a new 1.0.4 version.

**Comment by dagwieers** [comment]
So, now that we improved PlayerInfo and the add-on is again faster (which was one of the reason I was looking into PlayerInfo before I realised today all video listings were slow since two weeks) we should think about releasing this.

No more testing new changes and improvements, but testing what we have and fixing issues :-)
(I'll put any ideas in the drawer until we have v2.3.0 out, I promise !)

**Comment by dagwieers** [comment]
The only PR I would like to see in v2.3.0 is #591, but we depend on Up Next being released first.

**Comment by dagwieers** [comment]
I fear this is going to become a Christmas release instead :-/

Hunting a strange unfollow issue now.

**Comment by mediaminister** [comment]
> Hunting a strange unfollow issue now.

If you can provide more info, I'll take a look at it.

**Comment by dagwieers** [comment]
You can follow a program just fine, but unfollowing a program simply doesn't work. It has no effect anymore.

**Comment by mediaminister** [comment]
Issue with Unfollow is introduced in https://github.com/pietje666/plugin.video.vrt.nu/commit/cb68948028cc3ec5a9372ecc57d0741b9a61ac18

**Comment by mediaminister** [comment]
Fixed unfollow issue in https://github.com/pietje666/plugin.video.vrt.nu/pull/617

**Comment by dagwieers** [comment]
Up Next v1.0.7 is proposed for release, let's hope this gets released soon.
That would be one more item ticked off our list.

A list of things to be wary off is available from this tracker: #616

**Comment by dagwieers** [comment]
Prepare for take-off.

**Pull request merged**
