### PR TITLE
Add screenshots

### LINKED ISSUE #107: Add 3 screenshots to the add-on
**Describe the bug**
Our listing on the Kodi website, as well as the add-on entry in the Kodi Add-on browser would look a lot nicer if it included 3 screenshots of the add-on.

So we need to select the 3 best views of the VRT.NU add-on that showcase it best:
- Main menu
- Video listing
- Live TV menu

Or any better suggestions?

### PR DESCRIPTION
**Pull request by dagwieers**
This PR includes:
- Screenshots for the VRT.NU addon
- Move icon and fanart to *resources/images/*

The screenshots are 720p images reduced in size using:

    convert -sampling-factor 4:2:0 -strip -quality 85 screenshot-01.orig.png screenshot-01.png

But still quite large, however they compare in size with screenshots of other plugins.

This fixes #107

### CODE REVIEW

**Comment by dagwieers** [comment]
Size difference is considerable, almost 10x larger:

    -rw-rw-r--. 1 dag dag 2351111 27 mrt 15:26 plugin.video.vrt.nu-1.7.0-15ae565.zip
    -rw-rw-r--. 2 dag dag  290358 26 mrt 20:08 plugin.video.vrt.nu-1.7.0.zip

**Comment by dagwieers** [comment]
Shrinking 50% (so reducing to 360p) using:

    convert -sampling-factor 4:2:0 -strip -quality 85 -resize 50% ~/Downloads/main-menu.png screenshot-01.png
    convert -sampling-factor 4:2:0 -strip -quality 85 -resize 50% ~/Downloads/video-listing.png screenshot-02.png
    convert -sampling-factor 4:2:0 -strip -quality 85 -resize 50% ~/Downloads/live-tv.png screenshot-03.png

gives:

    -rw-rw-r--. 2 dag dag 290358 26 mrt 20:08 plugin.video.vrt.nu-1.7.0.zip
    -rw-rw-r--. 1 dag dag 850430 27 mrt 15:31 plugin.video.vrt.nu-1.7.0-15ae565.zip

**Comment by mediaminister** [comment]
Why shrinking?
My eyes need 1080p
If there are size limitations for the repository, maybe `pngquant` can provide better quality with lower file sizes.

**Comment by pietje666** [comment]
Its only visible in the information about the addon directory. I really doubt alot of people will care about the quality. (i only checked it from laptop screen though)

**Comment by dagwieers** [comment]
@mediaminister It's a tradeoff, I did not want the screenshots to take 90% of the size of our codebase. But it is true that 360p is very blurry on 1080p in Kodi itself. Still I wonder how much people actually click on the screenshots in Kodi. But I am all for higher quality with low file sizes so maybe we can do better. (That is why I shared the commands)
- I made the screenshots in 720p on purpose, hoping that shrinking would lead to better results
- I used Dutch language as that's what most people will be using anyway

**Comment by dagwieers** [comment]
I just tested with pngquant and it's a very big improvement. Size are somewhat larger, but still 720p.

-rw-rw-r--. 1 dag dag 290202 28 mrt 04:15 plugin.video.vrt.nu-1.7.1.zip
-rw-rw-r--. 1 dag dag 1067846 29 mrt 01:20 plugin.video.vrt.nu-1.7.1-ce06cce.zip

**Comment by dagwieers** [comment]
After tweaking and testing a lot of options and combinations, I think I am the most satisfied with this tradeoff using:

    pngquant --posterize 0 --quality 65 --speed 1 --force live-tv.png

This results in:

-rw-rw-r--. 1 dag dag 290202 28 mrt 04:15 plugin.video.vrt.nu-1.7.1.zip
-rw-rw-r--. 1 dag dag 684180 29 mrt 01:39 plugin.video.vrt.nu-1.7.1-ce06cce.zip

So that is my propsal, see #107 for the images.

**Comment by dagwieers** [comment]
Next up is improving the addon descriptions, the README intro, etc.

**Comment by pietje666** [comment]
Im fine with any decision about the screenshots btw

**Comment by mediaminister** [comment]
Maybe jpeg is more efficient than png for screenshots with video stills

**Comment by dagwieers** [comment]
But PNGs compress better. So another trade-off to be made ;-)

**Pull request merged**
